@echo off
rem generic script to build a contrib with MSVC.
rem

setlocal

set ABLOCALCOMPILEOPT=/c /nologo /Fo"%ABINTPATH%" /Fd"%ABINTPATH%"

IF DEFINED ABPCH (
	%ABCOMPILER% %ABLOCALCOMPILEOPT% %ABCOMPILEOPTS% %ABPREPROCDEF% %ABPCHSRC% /Yc"%ABPCH%" /Fp"%ABINTPATH%%ABPROJNAME%.pch"
	IF ERRORLEVEL 1 goto :ERR
	set ABCOMPILEOPTS=%ABCOMPILEOPTS% /Yu"%ABPCH%" /Fp%ABINTPATH%%ABPROJNAME%.pch
)

%ABCOMPILER% %ABLOCALCOMPILEOPT% %ABCOMPILEOPTS% %ABPREPROCDEF% %ABSRCS%
IF ERRORLEVEL 1 goto :ERR

IF %ABSTATIC% == 1 (
	%ABLINKER% %ABLINKERDEFOPTS% /OUT:"%ABLIBPATH%%ABLIBNAME%" "%ABINTPATH%*.obj" %ABLIBOPTS%
) ELSE (
	%ABLINKER% %ABLINKERDEFOPTS% /OUT:"%ABBINPATH%%ABDLLNAME%" "%ABINTPATH%*.obj" %ABLIBOPTS%
)
IF ERRORLEVEL 1 goto :ERR

goto :END

:ERR
endlocal
exit /b 1

:END
endlocal
